package projeto_agendacontatos;

import controle.ControleContato;
import modelos.Contato;
import modelos.Endereco;
import modelos.Telefone;
import persistencia.ContatoDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.List;

public class TelaAgenda extends javax.swing.JFrame {
    private static final int COLUNA_TELEFONE_INDEX = 1;
    private ControleContato controleContato;
    private DefaultTableModel modeloTabela;
    public Class<?> getColumnClass(int columnIndex) {
        return columnIndex == COLUNA_TELEFONE_INDEX ? String.class : Object.class;
    }

    public TelaAgenda() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        controleContato = new ControleContato(new ContatoDAO());
        modeloTabela = (DefaultTableModel) jTable_Agenda.getModel();
        MaskFormatter mask = new MaskFormatter("+55(##)#####-####");
        mask.install(jFormattedTextField_Telefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_NomeCompleto = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Agenda = new javax.swing.JTable();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jFormattedTextField_Telefone = new javax.swing.JFormattedTextField();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Logradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Complemento = new javax.swing.JTextField();
        jTextField_Cep = new javax.swing.JTextField();
        jTextField_Cidade = new javax.swing.JTextField();
        jTextField_Estado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_PDF = new javax.swing.JButton();
        jButton_Consulta = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Agenda Torcida Organizada");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Nome Completo: ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jTable_Agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "Email", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Agenda);

        jButton_Incluir.setText("Incluir");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Listar.setText("Listar");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });

        jFormattedTextField_Telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField_TelefoneMouseClicked(evt);
            }
        });

        jButton_Alterar.setText("Alterar");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Logradouro:");

        jLabel7.setText("Número:");

        jLabel8.setText("Complemento:");

        jLabel9.setText("Cep:");

        jLabel10.setText("Cidade:");

        jLabel11.setText("Estado:");

        jLabel5.setText("Endereço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Complemento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jButton_PDF.setText("PDF");
        jButton_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PDFActionPerformed(evt);
            }
        });

        jButton_Consulta.setText("Consultar");
        jButton_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addGap(0, 328, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_NomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Incluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Listar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_PDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Consulta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_NomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Incluir)
                            .addComponent(jButton_Listar)
                            .addComponent(jButton_Alterar)
                            .addComponent(jButton_Excluir)
                            .addComponent(jButton_PDF)
                            .addComponent(jButton_Consulta)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


     private void adicionarContato() {
    String nome = jTextField_NomeCompleto.getText();
    String telefone = jFormattedTextField_Telefone.getText();
    String email = jTextField_Email.getText();
    String logradouro = jTextField_Logradouro.getText();
    int numero = Integer.parseInt(jTextField_Numero.getText());
    String complemento = jTextField_Complemento.getText();
    int cep = Integer.parseInt(jTextField_Cep.getText());
    String cidade = jTextField_Cidade.getText();
    String estado = jTextField_Estado.getText();

    if (nome.isEmpty() || telefone.isEmpty() || email.isEmpty() || logradouro.isEmpty() || cidade.isEmpty() || estado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos, exceto o complemento!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (telefone.length() != 17) {
        JOptionPane.showMessageDialog(this, "O telefone deve ter 17 caracteres com a formatação!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!controleContato.verificarEmail(email)) {
        JOptionPane.showMessageDialog(this, "Email inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ajuste da formatação do número de telefone
    int ddi = Integer.parseInt(telefone.substring(1, 3));
    int ddd = Integer.parseInt(telefone.substring(4, 6));
    String numeroTelefone = telefone.substring(7, 17);
    Telefone telefoneObj = new Telefone(ddi, ddd, numeroTelefone);

    Endereco endereco = new Endereco(logradouro, numero, complemento, cep, cidade, estado);
    Contato contato = new Contato(nome, telefoneObj, email, endereco);
    controleContato.adicionar(contato);
    JOptionPane.showMessageDialog(this, "Contato adicionado com sucesso!");
    listarContatos();
}
private void listarContatos() {
    List<Contato> contatos = controleContato.listar();
    modeloTabela.setRowCount(0);
    for (Contato contato : contatos) {
        modeloTabela.addRow(new Object[]{contato.getNome(), formatarTelefone(contato.getTelefone()), contato.getEmail(), contato.getEndereco().toString()});
    }
}

private String formatarTelefone(Telefone telefone) {
    if (telefone != null) {
        String numeroFormatado = telefone.getNumero();
        return "+" + telefone.getDdi() + "(" + telefone.getDdd() + ")" + numeroFormatado;
    } else {
        return "";
    }
}
    private void deletarContato() {
        String nome = JOptionPane.showInputDialog(this, "Digite o nome do contato a ser deletado:", "Deletar Contato", JOptionPane.QUESTION_MESSAGE);
        if (nome != null && !nome.trim().isEmpty()) {
            controleContato.deletar(nome);
            JOptionPane.showMessageDialog(this, "Contato deletado com sucesso!");
            listarContatos(); // Atualiza a lista de contatos
        } else {
            JOptionPane.showMessageDialog(this, "Nome inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarContato() {
    String nome = JOptionPane.showInputDialog(this, "Digite o nome do contato a ser alterado:", "Alterar Contato", JOptionPane.QUESTION_MESSAGE);
    if (nome != null && !nome.trim().isEmpty()) {
        List<Contato> contatos = controleContato.listar();
        Contato contatoExistente = null;
        for (Contato contato : contatos) {
            if (contato.getNome().equalsIgnoreCase(nome.trim())) {
                contatoExistente = contato;
                break;
            }
        }
        if (contatoExistente != null) {
            try {
                String novoEmail = JOptionPane.showInputDialog(this, "Digite o novo email:", contatoExistente.getEmail());

                // Criando um JFormattedTextField para o novo telefone com a máscara adequada
                MaskFormatter mascaraTelefone = new MaskFormatter("+55 (##) #####-####");
                mascaraTelefone.setPlaceholderCharacter('_'); // Define um caractere para espaços vazios
                JFormattedTextField textFieldTelefone = new JFormattedTextField(mascaraTelefone);
                textFieldTelefone.setColumns(17); // Define o tamanho do campo para a máscara de telefone
                textFieldTelefone.setText(contatoExistente.getTelefone().toString());

                JOptionPane.showMessageDialog(this, textFieldTelefone, "Digite o novo telefone:", JOptionPane.PLAIN_MESSAGE);

                String novoTelefone = textFieldTelefone.getText();

                String novoLogradouro = JOptionPane.showInputDialog(this, "Digite o novo logradouro:", contatoExistente.getEndereco().getLogradouro());
                int novoNumero = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o novo número:", contatoExistente.getEndereco().getNumero()));
                String novoComplemento = JOptionPane.showInputDialog(this, "Digite o novo complemento:", contatoExistente.getEndereco().getComplemento());
                int novoCep = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o novo CEP:", String.valueOf(contatoExistente.getEndereco().getCep())));
                String novaCidade = JOptionPane.showInputDialog(this, "Digite a nova cidade:", contatoExistente.getEndereco().getCidade());
                String novoEstado = JOptionPane.showInputDialog(this, "Digite o novo estado:", contatoExistente.getEndereco().getEstado());

                // Remove os caracteres não numéricos do número de telefone
                String novoNumeroTelefone = novoTelefone.replaceAll("\\D", "");

                // Extrai o DDI, DDD e número do telefone
                int ddi = Integer.parseInt(novoNumeroTelefone.substring(0, 2));
                int ddd = Integer.parseInt(novoNumeroTelefone.substring(2, 4));
                String numero = novoNumeroTelefone.substring(4);

                // Instancia o objeto Telefone com os dados corrigidos
                Telefone telefoneObj = new Telefone(ddi, ddd, numero);
                
                Endereco endereco = new Endereco(novoLogradouro, novoNumero, novoComplemento, novoCep, novaCidade, novoEstado);
                Contato contatoAlterado = new Contato(nome, telefoneObj, novoEmail, endereco);
                controleContato.alterar(contatoExistente, contatoAlterado); // Passa o contatoExistente para identificar o contato a ser alterado
                JOptionPane.showMessageDialog(this, "Contato alterado com sucesso!");
                listarContatos(); // Atualiza a lista de contatos
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Contato não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Nome inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void consultarContato() {
    String nome = JOptionPane.showInputDialog(this, "Digite o nome do contato:", "Consultar Contato", JOptionPane.QUESTION_MESSAGE);
    if (nome != null && !nome.trim().isEmpty()) {
        Contato contato = controleContato.consultar(nome);
        if (contato != null) {
            JOptionPane.showMessageDialog(this, "Contato encontrado:\n" + contato.toString(), "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Contato não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Nome inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    private void criarPdf() {
        List<Contato> contatos = controleContato.listar();
        controleContato.criarPdf(contatos);
        JOptionPane.showMessageDialog(this, "PDF criado com sucesso!");
    }

    private void abrirPdf() {
        String filePath = "contatos.pdf"; // O caminho para o arquivo PDF gerado
        controleContato.abrirPdf(filePath);
    }

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        adicionarContato();
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarActionPerformed
        // TODO add your handling code here:
        listarContatos();
    }//GEN-LAST:event_jButton_ListarActionPerformed

    private void jFormattedTextField_TelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField_TelefoneMouseClicked
        jFormattedTextField_Telefone.setCaretPosition(4);
    }//GEN-LAST:event_jFormattedTextField_TelefoneMouseClicked

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        alterarContato();
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        deletarContato();
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PDFActionPerformed
       criarPdf();
       abrirPdf();
    }//GEN-LAST:event_jButton_PDFActionPerformed

    private void jButton_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaActionPerformed
      consultarContato();
    }//GEN-LAST:event_jButton_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaAgenda().setVisible(true);
            } catch (ParseException ex) {
                // Em vez de logar, você pode exibir uma mensagem de erro
                JOptionPane.showMessageDialog(null, "Erro ao iniciar a tela de agenda", "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace(); // Apenas para depuração, você pode remover isso em um ambiente de produção
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Consulta;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JButton jButton_PDF;
    private javax.swing.JFormattedTextField jFormattedTextField_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Agenda;
    private javax.swing.JTextField jTextField_Cep;
    private javax.swing.JTextField jTextField_Cidade;
    private javax.swing.JTextField jTextField_Complemento;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Estado;
    private javax.swing.JTextField jTextField_Logradouro;
    private javax.swing.JTextField jTextField_NomeCompleto;
    private javax.swing.JTextField jTextField_Numero;
    // End of variables declaration//GEN-END:variables
}